package edu.arizona.sista.odin.domains.bigmechanism.summer2015

/**
  * Trait for defining constants used by grounding and entity checking code.
  *   Written by Tom Hicks. 5/26/2015.
  *   Last Modified: Initial creation.
  */
trait KnowledgeBaseConstants {

  /** The set of characters to remove from the text to create a lookup key. */
  val KeyCharactersToRemove = " /-".toSet

  /** The set of words to remove from the text to create a lookup key. */
  val KeyStopSuffixes = Set("_human")

  /** The set of words to remove from the text to create a lookup key. */
  val HumanLabels = Set("homo sapiens", "human")


  /** Path the the directory which hold the entity knowledge bases. */
  val KBDirectory = "/edu/arizona/sista/odin/domains/bigmechanism/summer2015/kb"

  /** Filename of the cellular location file generated by the entity checker. */
  val CellLocationFilename = "biopax-cellular_component.tsv"
  /** Prefix string for cellular location IDs generated by the entity checker. */
  val CellLocationPrefix = "UA-BP-CC-"

  /** Filename of the small molecule file generated by the entity checker. */
  val ChemicalFilename = "biopax-simple_chemical.tsv"
  /** Prefix string for small molecule IDs generated by the entity checker. */
  val ChemicalPrefix = "UA-BP-SC-"

  /** Filename of the protein/family file generated by the entity checker. */
  val ProteinFilename = "biopax-gene_or_gene_product.tsv"
  /** Prefix string for protein/family IDs generated by the entity checker. */
  val ProteinPrefix = "UA-BP-GGP-"

}
