package edu.arizona.sista.reach.grounding

/**
  * Trait for defining constants used by grounding and entity checking code.
  *   Written by Tom Hicks. 10/22/2015.
  *   Last Modified: Add bio process KB constant.
  */
object ReachKBConstants {

  /** The default namespace string for KBs. */
  val DefaultNamespace: String = "uaz"


  /** The set of words to remove from all keys to create a lookup key. */
  val AllKeysStopSuffixes = Seq("_human")

  /** The set of words to remove from a key to create a protein family lookup key. */
  val FamilyStopSuffixes = Seq(" protein family", " family")

  /** The set of characters to remove from the text to create a lookup key. */
  val KeyCharactersToRemove = " /-".toSet

  /** The set of words to remove from a key to create a protein lookup key. */
  val ProteinStopSuffixes = Seq(" mutant protein", " protein")


  /** File Path to the directory which holds the entity knowledge bases. */
  val KBDirFilePath = "src/main/resources/edu/arizona/sista/reach/kb"

  /** Resource Path to the directory which holds the entity knowledge bases. */
  val KBDirResourcePath = "/edu/arizona/sista/reach/kb"


  /** Filename of the cellular location file generated by the entity checker. */
  val GendCellLocationFilename = "biopax-cellular_component.tsv"
  /** Prefix string for cellular location IDs generated by the entity checker. */
  val GendCellLocationPrefix = "UA-BP-CC-"

  /** Filename of the small molecule file generated by the entity checker. */
  val GendChemicalFilename = "biopax-simple_chemical.tsv"
  /** Prefix string for small molecule IDs generated by the entity checker. */
  val GendChemicalPrefix = "UA-BP-SC-"

  /** Filename of the protein/family file generated by the entity checker. */
  val GendProteinFilename = "biopax-gene_or_gene_product.tsv"
  /** Prefix string for protein/family IDs generated by the entity checker. */
  val GendProteinPrefix = "UA-BP-GGP-"


  /** Filename of the manually maintained cellular location file. */
  val ManualCellLocationFilename = "manual-cellular_component.tsv"

  /** Filename of the manually maintained small molecule file. */
  val ManualChemicalFilename = "manual-simple_chemical.tsv"

  /** Filename of the manually maintained protein file. */
  val ManualProteinFilename = "manual-gene_or_gene_product.tsv"

  /** Filename of the manually maintained protein family file. */
  val ManualProteinFamilyFilename = "manual-family.tsv"


  /** Filename of the static bio processes file. */
  val StaticBioProcessFilename = "bio_process.tsv"

  /** Filename of the static cellular location file. */
  val StaticCellLocationFilename = "GO-subcellular-locations.tsv"

  /** Filename of the alternate static cellular location file. */
  val StaticCellLocation2Filename = "uniprot-subcellular-locations.tsv"

  /** Filename of the static small molecule (chemical) file. */
  val StaticChemicalFilename = "chebi.tsv.gz"

  /** Filename of the static small molecule (chemical) file. */
  val StaticMetaboliteFilename = "hmdb.tsv.gz"

  /** Filename of the static protein file. */
  val StaticProteinFilename = "uniprot-proteins.tsv.gz"

  /** Filename of the static protein family file. */
  val StaticProteinFamilyFilename = "ProteinFamilies.tsv.gz"

  /** Filename of the static tissue type file. */
  val StaticTissueTypeFilename = "tissue-type.tsv"


 /** Filename of the context species file */
  val ContextSpeciesFilename = "Species.tsv.gz"

  /** Filename of the contenxt cell lines file */
  val ContextCellLineFilename = "Cell_Lines.tsv"

  /** Filename of the context cell types file */
  val ContextCellTypeFilename = "Cell_Type.tsv"

  /** Filename of the context organs file */
  val ContextOrganFilename = "Organ.tsv"

}
